### ISSUE TITLE
Large requests cause 500

### ISSUE THREAD

**Issue by Cydrobolt** [fedora-infra/datagrepper#160]
e.g https://apps.fedoraproject.org/datagrepper/raw?delta=10000972800&user=cydrobolt

**Comment by ralphbean** [comment]
This should hopefully be fixed when [these optimizations](http://threebean.org/blog/revisiting-datagrepper-performance/) get rolled out.

**Comment by ralphbean** [comment]
#169 would help here.

**Comment by ralphbean** [comment]
Here's the exception:

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/datagrepper/app.py", line 211, in raw
    start, end, delta = assemble_timerange(start, end, delta)
  File "/usr/lib/python2.7/site-packages/datagrepper/util.py", line 65, in assemble_timerange
    then = datetime_to_seconds(end - delta)
  File "/usr/lib/python2.7/site-packages/datagrepper/util.py", line 30, in datetime_to_seconds
    return time.mktime(dt.timetuple())
ValueError: year out of range
```

That's... more or less a valid complaint from datagrepper.  I'm going to go ahead and close this one as wontfix since:

1) datagrepper doesn't have anything sensible to do if you ask it for messages from before the beginning of time.
2) #169 will help expose the reason for the error to the user so they can know what to do.
