### ISSUE TITLE
datagrepper unable to grep data

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/datagrepper#190]
I am using [this](https://pnemade.fedorapeople.org/userwat.py) script. I am getting messages around 300 every time I ran it.  For all those messages I got, they showed status_code 200 but then after sometime suddenly it changes to 500 and breaks as
```
response.status_code is 500
Traceback (most recent call last):
  File "userwat.py", line 51, in <module>
    main(username)
  File "userwat.py", line 38, in main
    for msg in results['raw_messages']:
KeyError: 'raw_messages'
```
The sample run output is available at [link](https://pnemade.fedorapeople.org/sample1.txt).

I am running this on Fedora 25 system. I ran the same script on some other user names like sandeeps, suanand, jcline and its running fine for them where they have no recorded messages for 2017-03-02 date.

Then I ran that script using these 3 FAS names pravins, ralph, puiterwijk and they all failed.

For pravins last message received is
2017-03-02T01:08:10 pagure.issue.new pravins opened a new ticket badges#260: <snip>

for ralph last message received is
2017-03-02T01:07:39 pagure.issue.comment.added ralph commented on ticket badges#109: <snip>

for puiterwijk last message received is
2017-03-02T01:08:01 pagure.issue.comment.added puiterwijk commented on ticket badges#227: <snip>

Can someone please check if datanommer is Okay for that date?

**Comment by pnemade** [comment]
Reported also at https://pagure.io/fedora-infrastructure/issue/5892

**Comment by pnemade** [comment]
This has worked today now but the mystery remained why it did not work for a month period.
