### ISSUE TITLE
Traceback in the logs

### ISSUE THREAD

**Issue by abompard** [fedora-infra/datagrepper#410]
```
10.3.166.75 - - [21/Jun/2022:12:26:14 +0000] "GET /datagrepper/v2/search?delta=1000&category=fas HTTP/1.1" 200 362 "-" "HTTPie/3.2.1"
Traceback (most recent call last):
  File "/opt/app-root/src/datagrepper/app.py", line 332, in raw
    total, pages, messages = dm.Message.grep(
  File "/opt/app-root/lib64/python3.9/site-packages/datanommer/models/__init__.py", line 497, in grep
    messages = query.all()
  File "/opt/app-root/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 2768, in all
    return self._iter().all()
  File "/opt/app-root/lib64/python3.9/site-packages/sqlalchemy/engine/result.py", line 1371, in all
    return self._allrows()
  File "/opt/app-root/lib64/python3.9/site-packages/sqlalchemy/engine/result.py", line 401, in _allrows
    rows = self._fetchall_impl()
  File "/opt/app-root/lib64/python3.9/site-packages/sqlalchemy/engine/result.py", line 1284, in _fetchall_impl
    return self._real_result._fetchall_impl()
  File "/opt/app-root/lib64/python3.9/site-packages/sqlalchemy/engine/result.py", line 1696, in _fetchall_impl
    return list(self.iterator)
  File "/opt/app-root/lib64/python3.9/site-packages/sqlalchemy/orm/loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "/opt/app-root/lib64/python3.9/site-packages/sqlalchemy/engine/result.py", line 393, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/opt/app-root/lib64/python3.9/site-packages/sqlalchemy/engine/result.py", line 393, in <listcomp>
    return [make_row(row) for row in rows]
  File "/opt/app-root/lib64/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 1686, in process
    return process_value(value, dialect)
  File "/opt/app-root/lib64/python3.9/site-packages/datanommer/models/__init__.py", line 184, in process_result_value
    value = json.loads(value)
  File "/usr/lib64/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```

**Comment by abompard** [comment]
My bad, the database schema in staging was not the latest schema, it was still using JSONB columns.
