### ISSUE TITLE
Error "FATAL:  database "datanommer" does not exist" while starting datagrepper project

### ISSUE THREAD

**Issue by novicejava1** [fedora-infra/datagrepper#610]
HI,
I am trying the run the datagrepper project as per the steps provided in the documentation but getting Error "FATAL:  database "datanommer" does not exist". Here are the steps that i followed.

1. Clone the datagrepper and datanommer repos

```
$ git clone https://github.com/fedora-infra/datagrepper.git
$ git clone https://github.com/fedora-infra/datanommer.git
```

2. Update fedora messaging config as per below

As per the following update in datanommer/datanommer.commands/news/PR815.feature file
```
"Use Alembic to stamp the database when creating it. This requires adding a config variable ``alembic_ini`` in the fedora-messaging configuration file that points to the ``alembic.ini`` file"
```

I have updated the fedora messaging config file with the alembic_ini reference.

```
[admin@fedora ~]$ vi datagrepper/devel/ansible/roles/datagrepper/templates/fedora-messaging.toml.j2
...
[consumer_config]
datanommer_sqlalchemy_url = "postgresql://datanommer:datanommer@localhost/messages"
alembic_ini = "../datanommer.models/alembic.ini"
...
```

3. Start the Project

```
$ cd datagrepper/
$ vagrant up
```

Error - As per the error it seems its unable to create the datanommer database and throwing the below error

```
TASK [datagrepper : Create datanommer db] **************************************
fatal: [datagrepper]: FAILED! => changed=true 
  cmd: /srv/venv/bin/poetry run datanommer-create-db
  delta: '0:00:03.497596'
  end: '2023-06-05 03:36:39.708374'
  msg: non-zero return code
  rc: 1
  start: '2023-06-05 03:36:36.210778'
  stderr: |-
    Traceback (most recent call last):
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
        return fn()
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
        return _ConnectionFairy._checkout(self)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
        fairy = _ConnectionRecord.checkout(pool)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
        rec = pool._do_get()
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
        return self._create_connection()
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
        return _ConnectionRecord(self)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
        self.__connect()
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
        pool.logger.debug("Error on connect(): %s", e)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
        compat.raise_(
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
        raise exception
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
        self.dbapi_connection = connection = pool._invoke_creator(self)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
        return dialect.connect(*cargs, **cparams)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
        return self.dbapi.connect(*cargs, **cparams)
      File "/srv/venv/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
        conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
    psycopg2.OperationalError: FATAL:  database "datanommer" does not exist
  
  
    The above exception was the direct cause of the following exception:
  
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/srv/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
        return self.main(*args, **kwargs)
      File "/srv/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
        rv = self.invoke(ctx)
      File "/srv/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/srv/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
        return __callback(*args, **kwargs)
      File "/home/vagrant/datanommer/datanommer.commands/datanommer/commands/__init__.py", line 58, in create
        m.init(
      File "/srv/venv/lib/python3.9/site-packages/datanommer/models/__init__.py", line 106, in init
        command.stamp(alembic_cfg, "head")
      File "/srv/venv/lib/python3.9/site-packages/alembic/command.py", line 671, in stamp
        script.run_env()
      File "/srv/venv/lib/python3.9/site-packages/alembic/script/base.py", line 569, in run_env
        util.load_python_file(self.dir, "env.py")
      File "/srv/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
        module = load_module_py(module_id, path)
      File "/srv/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
        spec.loader.exec_module(module)  # type: ignore
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/srv/venv/lib/python3.9/site-packages/datanommer/models/alembic/env.py", line 93, in <module>
        run_migrations_online()
      File "/srv/venv/lib/python3.9/site-packages/datanommer/models/alembic/env.py", line 80, in run_migrations_online
        connection = engine.connect()
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
        return self._connection_cls(self, close_with_result=close_with_result)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
        else engine.raw_connection()
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
        return self._wrap_pool_connect(self.pool.connect, _connection)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3364, in _wrap_pool_connect
        Connection._handle_dbapi_exception_noconnection(
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 2198, in _handle_dbapi_exception_noconnection
        util.raise_(
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
        raise exception
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
        return fn()
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
        return _ConnectionFairy._checkout(self)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
        fairy = _ConnectionRecord.checkout(pool)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
        rec = pool._do_get()
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
        return self._create_connection()
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
        return _ConnectionRecord(self)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
        self.__connect()
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
        pool.logger.debug("Error on connect(): %s", e)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
        compat.raise_(
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
        raise exception
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
        self.dbapi_connection = connection = pool._invoke_creator(self)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
        return dialect.connect(*cargs, **cparams)
      File "/srv/venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
        return self.dbapi.connect(*cargs, **cparams)
      File "/srv/venv/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
        conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
    sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "datanommer" does not exist
  
    (Background on this error at: https://sqlalche.me/e/14/e3q8)
  stderr_lines: <omitted>
  stdout: Creating Datanommer database and tables
  stdout_lines: <omitted>
```

Complete vagrant log output [gist](https://gist.github.com/novicejava1/6caf4d1de7f1caef237855283df7d780)

Please suggest if i am missing anything here

**Comment by novicejava1** [comment]
Seems the default alembic.ini file from datanommer project has the following url - "sqlalchemy.url = postgresql://datanommer:datanommer@localhost/datanommer".  Updated it to "sqlalchemy.url = postgresql://datanommer:datanommer@localhost/messages" as messages is the database that we are creating to store the fedora messaging queue messages and after that vagrant up was successful
