### ISSUE TITLE
Add a page to list all the topics

### ISSUE THREAD

**Issue by abompard** [fedora-infra/datagrepper#676]
It would be nice to have a page that would basically be the result of `SELECT DISTINCT topic FROM messages` with a time delta. Having it as an API endpoint would make it even more useful, to know what's available.

**Comment by asamalik** [comment]
That would be really useful to discover what topics exist, I'd love that!

**Comment by MundiaNderi** [comment]
Hey @abompard and @asamalik Is this issue still open and up to date? I'd like to work on it as an Outreachy intern.

**Comment by abompard** [comment]
Yes, that is still a valid issue to pick from. Please assign it to yourself using the link at the top of the right column.

**Comment by NoubissiViany** [comment]
Hi, @abompard and @asamalik. Is this issue still active and up to date? I would like to work on it as an Outreachy intern.

**Comment by Solar-Rays** [comment]
Hi @abompard @asamalik Can I work on this also please?

**Comment by anshikavashistha** [comment]
I want to work on this issue. @abompard please assign this to me

**Comment by damilareogaga** [comment]
Please assign this issue to me @abompard

**Comment by anshikavashistha** [comment]
I am working on it 
@abompard @asamalik

**Comment by abompard** [comment]
Hey @MundiaNderi , are you still interested? Have you started working on it?

**Comment by Precious000** [comment]
Hi @abompard appears this has not been assigned yet, can you please assign it to me? I’m an outreachy intern and would love to work on it. Thanks

**Comment by MundiaNderi** [comment]
Hey @abompard Thank you for assigning the task to me. I had started another Outreachy task by the time you replied that I'm still working on. Since @anshikavashistha had already started on it, my suggestion is that they continue working on it.

**Comment by abompard** [comment]
I've been contacted by @anshikavashistha and she's working on something else now. I'm going to go through the comments by date then. Are you still interested @NoubissiViany ?

**Comment by NoubissiViany** [comment]
@abompard yes i’m still interested

**Comment by abompard** [comment]
Alright, go ahead! :-)

**Comment by NoubissiViany** [comment]
Okay thanks very much.

**Comment by princyym** [comment]
Hello @abompard , I am a beginner and I want to work on this issue can you assign it to me.

**Comment by abompard** [comment]
Hi @princyym , it's unfortunately already assigned. @NoubissiViany do you still want to work on it?

**Comment by NoubissiViany** [comment]
@abompard Yes I am, please I need more details on the issue. For example, in which language are we going to create the endpoint and in which folder are we specifically going to work? I'm lost at a certain point

**Comment by abompard** [comment]
Hey @NoubissiViany , are you still interested or should I unassign you so that other can work on it?

**Comment by NoubissiViany** [comment]
You can unassign it to me.

**Comment by abompard** [comment]
If we want to have a representative view of the topic, I think we should make a materialized view in datanommer/postgresql for the list of messages over the past year, and add to that the number of messages in each topic.

Having a materialized view would help with the cost of the query.

**Comment by sdglitched** [comment]
Hey @abompard,

This issue seems to be open and unassigned. Is it up for grabs?

For creating an materialized view in `datanommer`, below snippet can be used (refresh of the materialized view is not included in it)

```python
class CreateMaterializedView(DDLElement):
    def __init__(self, name, selectable):
        self.name = name
        self.selectable = selectable


class DropMaterializedView(DDLElement):
    def __init__(self, name):
        self.name = name


@compiler.compiles(CreateMaterializedView)
def _create_view(element, compiler, **kw):
    return "CREATE MATERIALIZED VIEW IF NOT EXISTS %s AS %s" % (
        element.name,
        compiler.sql_compiler.process(element.selectable, literal_binds=True),
    )


@compiler.compiles(DropMaterializedView)
def _drop_view(element, compiler, **kw):
    return "DROP VIEW %s" % (element.name)


def view_exists(ddl, target, connection, **kw):
    return ddl.name in inspect(connection).get_view_names()


def view_doesnt_exist(ddl, target, connection, **kw):
    return not view_exists(ddl, target, connection, **kw)


def view(name, metadata, selectable):
    table = Table(
        name,
        metadata,
        *(
            Column(column.name, column.type, primary_key=column.primary_key)
            for column in selectable.selected_columns
        ),
    )

    event.listen(
        metadata,
        "after_create",
        CreateMaterializedView(name, selectable).execute_if(callable_=view_doesnt_exist),
    )
    event.listen(
        metadata,
        "before_drop",
        DropMaterializedView(name).execute_if(callable_=view_exists),
    )
    return table


recent_topics = view(
        "recent_topics",
        DeclarativeBase.metadata,
        select(
            Message.topic,
            func.count().label("message_count")
        ).where(
            Message.timestamp >= text("NOW() - INTERVAL '1 year'")
        ).group_by(Message.topic),
    )
```

![Image](https://github.com/user-attachments/assets/dba33bc6-672a-4721-aac7-cf6826817b8f)

Is this something you were looking for? If yes, should I open a PR in `datanommer`?

I also wanted to test the view with some actual/dummy data. Is is possible to share some dump with me?

**Comment by abompard** [comment]
Very interesting, thanks! I'll test that too. What we also need to do:
- migration with alembic
- refresh the view when a new message gets inserted (manually in datanommer or with a SQLAlchemy trigger)
- make really sure that refreshing the view does not impact insertion speed. If it does, refresh it asynchronously, for example on a timer or periodically. 

And yeah you can open a PR in datanommer if you don't mind. Thanks again!

**Comment by sdglitched** [comment]
Sure, I'll raise a PR in datanommer with the alembic migration and refresh functionality.

**Comment by sdglitched** [comment]
Hey @abompard!

I was trying to apply migration using alembic but I'm facing some issues.

As per the [alembic.ini](https://github.com/fedora-infra/datanommer/blob/1d010481eb601f454fd86f6cb903440bdb83454f/datanommer.models/alembic.ini#L14) the database should be named `datanommer`, but while trying to check the current migration version I getting below traceback.
```shell
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/venv/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/srv/venv/lib/python3.11/site-packages/alembic/config.py", line 636, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/srv/venv/lib/python3.11/site-packages/alembic/config.py", line 626, in main
    self.run_cmd(cfg, options)
  File "/srv/venv/lib/python3.11/site-packages/alembic/config.py", line 603, in run_cmd
    fn(
  File "/srv/venv/lib/python3.11/site-packages/alembic/command.py", line 634, in current
    script.run_env()
  File "/srv/venv/lib/python3.11/site-packages/alembic/script/base.py", line 586, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/srv/venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/vagrant/datanommer/datanommer.models/datanommer/models/alembic/env.py", line 93, in <module>
    run_migrations_online()
  File "/home/vagrant/datanommer/datanommer.models/datanommer/models/alembic/env.py", line 80, in run_migrations_online
    connection = engine.connect()
                 ^^^^^^^^^^^^^^^^
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 3274, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 2439, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/pool/impl.py", line 308, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
    self.__connect()
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    with util.safe_reraise():
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/venv/lib64/python3.11/site-packages/sqlalchemy/engine/default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/venv/lib64/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "datanommer" does not exist
```
Even after deleting the vagrant setup and re-provisioning it, I'm facing the same. Not sure if I'm doing something wrong while setup.

One thing I noticed is that database naming `messages` is created and if I change the sqlalchemy.url as `sqlalchemy.url = postgresql://datanommer:datanommer@localhost/messages` I can see the latest migration as per the versions
```shell
(venv) [vagrant@datanommer datanommer.models]$ alembic current
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
429e6f2cba6f (head)
(venv) [vagrant@datanommer datanommer.models]$
(venv) [vagrant@datanommer datanommer.models]$ psql -h localhost -d datanommer -U datanommer
Password for user datanommer: 
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "datanommer" does not exist
(venv) [vagrant@datanommer datanommer.models]$ 
(venv) [vagrant@datanommer datanommer.models]$ psql -h localhost -d messages -U datanommer
psql (15.4)
Type "help" for help.

messages=> \l
                                                  List of databases
   Name    |   Owner    | Encoding |   Collate   |    Ctype    | ICU Locale | Locale Provider |   Access privileges   
-----------+------------+----------+-------------+-------------+------------+-----------------+-----------------------
 messages  | datanommer | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | 
 postgres  | postgres   | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | 
 template0 | postgres   | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | =c/postgres          +
           |            |          |             |             |            |                 | postgres=CTc/postgres
 template1 | postgres   | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | =c/postgres          +
           |            |          |             |             |            |                 | postgres=CTc/postgres
(4 rows)

messages=>
```

Could you maybe point me to the correct direction? If you need any other information from me, please let me know.

**Comment by sdglitched** [comment]
Also, it seems in the vagrant/ansible setup, the database name used is `messages` in the sqlalchemy.url in [alembic.ini](https://github.com/fedora-infra/datanommer/blob/1d010481eb601f454fd86f6cb903440bdb83454f/devel/ansible/roles/datanommer/files/alembic.ini#L14). Whereas the database name is `datanommer` in the sqlalchemy.url in [alembic.ini](https://github.com/fedora-infra/datanommer/blob/1d010481eb601f454fd86f6cb903440bdb83454f/datanommer.models/alembic.ini#L14) inside the datanommer.models.

Could it be that database name is not setup correctly? Or am I missing something?

**Comment by mwinters0** [comment]
Please see https://forge.fedoraproject.org/fdwg/datanommer-ops/src/branch/main/docs/facts/topics.txt and join us in the FDWG matrix room [`#data`](https://matrix.to/#/%23data:fedoraproject.org)!  We have all of this.
